<%#
 Copyright 2018 the original author or authors from the Simlife project.

 This file is part of the Simlife project, see https://www.simlife.io/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
FROM <%= DOCKER_JAVA_JRE %>

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    SIMLIFE_SLEEP=0 \
    JAVA_OPTS="<%_ if (cacheProvider === 'infinispan') { _%>-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true<%_ } _%>"

# Add a simlife user to run our application so that it doesn't need to run as root
RUN adduser -D -s /bin/sh simlife
WORKDIR /home/simlife

ADD entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh && chown simlife:simlife entrypoint.sh
USER simlife

ADD *.war app.war

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE <%= serverPort %><% if (cacheProvider === 'hazelcast') { %> 5701/udp<% } %>

